#!/bin/bash
# FreeRADIUS + MySQL + LDAP Setup Script with Full Configuration
# Author: Locas Potter (Generated by ChatGPT)
# Description: Installs and configures FreeRADIUS with MySQL and LDAP, imports schema, and applies all predefined configs.

set -e
set -o pipefail

ENV_FILE=".env"

# --------------------
# Load .env variables - FIXED VERSION
# --------------------
if [ ! -f "$ENV_FILE" ]; then
    echo "[ERROR] $ENV_FILE not found. Please create it first."
    echo "[INFO] Required .env variables:"
    echo "  MYSQL_ROOT_PASSWORD=your_root_password"
    echo "  RADIUS_DB_PASSWORD=your_radius_db_password"
    echo "  LDAP_SERVER=ldap://your-ldap-server"
    echo "  LDAP_IDENTITY=your-ldap-identity"
    echo "  LDAP_PASSWORD=your-ldap-password"
    echo "  LDAP_BASE_DN=DC=your,DC=domain"
    echo "  LDAP_USER_FILTER=your-filter-here (optional)"
    echo "  RADIUS_Secret=your_radius_secret"
    exit 1
fi

# Improved .env loading that handles special characters
echo "[INFO] Loading environment variables from $ENV_FILE..."
while IFS= read -r line; do
    # Skip comments and empty lines
    [[ "$line" =~ ^#.*$ ]] || [[ -z "$line" ]] && continue
    
    # Remove leading/trailing whitespace
    line=$(echo "$line" | xargs)
    
    # Split on first '='
    key="${line%%=*}"
    value="${line#*=}"
    
    # Remove quotes from value if present
    value="${value%\"}"
    value="${value#\"}"
    value="${value%\'}"
    value="${value#\'}"
    
    # Trim whitespace from key and value
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    
    # Export the variable
    export "$key"="$value"
    echo "[DEBUG] Loaded: $key"
done < "$ENV_FILE"

# Alternative simpler method if above doesn't work:
# echo "[INFO] Using alternative .env loading method..."
# set -a  # Automatically export all variables
# source "$ENV_FILE"
# set +a

# Check required variables
REQUIRED_VARS=("MYSQL_ROOT_PASSWORD" "RADIUS_DB_PASSWORD" "LDAP_SERVER" "LDAP_IDENTITY" "LDAP_PASSWORD" "LDAP_BASE_DN" "RADIUS_Secret")
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        echo "[ERROR] $var is not set in .env"
        exit 1
    fi
done

# Set defaults for optional variables if not set
if [ -z "${LDAP_USER_FILTER}" ]; then
    LDAP_USER_FILTER="(&(sAMAccountName=%{%{Stripped-User-Name}:-%{User-Name}}))"
fi

# Get IP from .env if available
IP=${IP:-$(hostname -I | awk '{print $1}')}

# Debug: Show loaded values (optional)
echo "[DEBUG] LDAP_USER_FILTER: $LDAP_USER_FILTER"
echo "[DEBUG] OPENVPN_AUTH: ${OPENVPN_AUTH:-not set}"
echo "[DEBUG] BIND_ADDRESS: ${BIND_ADDRESS:-not set}"
echo "[DEBUG] REMOTE_ROOT_IP: ${REMOTE_ROOT_IP:-not set}"
echo "[DEBUG] RADIUS_Secret: [set]"
echo "[DEBUG] IP: $IP"

# --------------------
# Update & Install Packages
# --------------------
echo "[INFO] Updating package list..."
sudo apt-get update -y

echo "[INFO] Installing FreeRADIUS, MySQL, and LDAP packages..."
sudo apt-get install -y freeradius freeradius-mysql freeradius-utils mysql-server freeradius-ldap

# --------------------
# Secure MySQL root account
# --------------------
echo "[INFO] Securing MySQL root account..."

if mysql -u root -e "SELECT 1;" >/dev/null 2>&1; then
    echo "[INFO] MySQL root account already secured."
else
    echo "[INFO] Setting MySQL root password..."
    sudo mysql -u root <<EOF
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ROOT_PASSWORD}';
FLUSH PRIVILEGES;
EOF
fi

# --------------------
# Allow remote root access (if specified)
# --------------------
if [ -n "$REMOTE_ROOT_IP" ]; then
    echo "[INFO] Granting root access from $REMOTE_ROOT_IP..."
    sudo mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF
CREATE USER IF NOT EXISTS 'root'@'${REMOTE_ROOT_IP}' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'${REMOTE_ROOT_IP}' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF
fi

# --------------------
# Create RADIUS database & user (idempotent)
# --------------------
echo "[INFO] Creating RADIUS database and user..."
sudo mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF
CREATE DATABASE IF NOT EXISTS radius CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'radius'@'localhost' IDENTIFIED BY '${RADIUS_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON radius.* TO 'radius'@'localhost';
FLUSH PRIVILEGES;
EOF

# --------------------
# Import FreeRADIUS schema
# --------------------
echo "[INFO] Importing FreeRADIUS schema..."
sudo mysql -u root -p"${MYSQL_ROOT_PASSWORD}" radius < /etc/freeradius/3.0/mods-config/sql/main/mysql/schema.sql

# --------------------
# Backup original files
# --------------------
echo "[INFO] Backing up original configuration files..."
BACKUP_DIR="/etc/freeradius/3.0/backup_$(date +%Y%m%d_%H%M%S)"
sudo mkdir -p "$BACKUP_DIR"

# Backup sites-available files
sudo cp -r /etc/freeradius/3.0/sites-available "$BACKUP_DIR/"
sudo cp -r /etc/freeradius/3.0/mods-available "$BACKUP_DIR/"
sudo cp -r /etc/freeradius/3.0/mods-config "$BACKUP_DIR/"

echo "[INFO] Backups saved to: $BACKUP_DIR"

# --------------------
# Configure sites-enabled/default
# --------------------
echo "[INFO] Configuring sites-enabled/default..."
sudo tee /etc/freeradius/3.0/sites-available/default >/dev/null <<'EOF'
server default {

listen {
    type = auth
    ipaddr = *
    port = 0
    limit {
        max_connections = 16
        lifetime = 0
        idle_timeout = 30
    }
}

listen {
    type = acct
    ipaddr = *
    port = 0
}

# Authorization
authorize {
    filter_username
    preprocess

    # LDAP for authentication
    ldap
    if (ok) {
        update control {
            Auth-Type := LDAP
        }
    }

    # SQL for reply attributes (e.g., Framed-IP-Address)
    sql
#    pap
    expiration
    logintime
}

# Authentication
authenticate {
    # PAP authentication
#    Auth-Type PAP {
#        pap
#    }

    Auth-Type LDAP {
        ldap
    }
}

# Accounting
accounting {
    detail
    acct_unique
    sql
    exec
    attr_filter.accounting_response
}

# Session tracking
session {
    sql
}

# Post-Authentication
post-auth {
    # Pull any session-state attributes into the reply
    if (session-state:User-Name && reply:User-Name && request:User-Name && (reply:User-Name == request:User-Name)) {
        update reply {
            &User-Name !* ANY
        }
    }
    update {
        &reply: += &session-state:
    }

    sql

    exec
    remove_reply_message_if_eap

    Post-Auth-Type REJECT {
        -sql
        attr_filter.access_reject
        eap
        remove_reply_message_if_eap
    }
}
}
EOF


# --------------------
# Configure Clients.conf with shared RADIUS secret
# --------------------
echo "[INFO] Configuring clients.conf with shared RADIUS secret..."
sudo tee /etc/freeradius/3.0/clients.conf>/dev/null <<EOF
# Localhost client
client localhost {
    ipaddr = 127.0.0.1
    proto = *
    secret = ${RADIUS_Secret}
    require_message_authenticator = yes
    nas_type = other
    shortname = localhost
}

# OpenVPN server (using IP from .env or detected)
client ${IP} {
    ipaddr = ${IP}
    secret = ${RADIUS_Secret}
    require_message_authenticator = yes
    nas_type = other
    shortname = openvpn-server
}

# Allow from local network (192.168.x.x)
client 192.168.0.0/16 {
    secret = ${RADIUS_Secret}
    require_message_authenticator = yes
    nas_type = other
    shortname = local-network
}

# Allow from VPN network (10.x.x.x)
client 10.0.0.0/8 {
    secret = ${RADIUS_Secret}
    require_message_authenticator = yes
    nas_type = other
    shortname = vpn-network
}
EOF

# --------------------
# Configure mods-enabled/ldap
# --------------------
echo "[INFO] Configuring mods-enabled/ldap..."
sudo tee /etc/freeradius/3.0/mods-available/ldap >/dev/null <<EOF
ldap {
    server = '${LDAP_SERVER}'
    identity = '${LDAP_IDENTITY}' # Username
    password = '${LDAP_PASSWORD}'

    base_dn = '${LDAP_BASE_DN}'

    update {
        control:Password-With-Header    += 'userPassword'
        control:                        += 'radiusControlAttribute'
        request:                        += 'radiusRequestAttribute'
        reply:                          += 'radiusReplyAttribute'
    }

    authenticate = yes
    user_dn = "LDAP-UserDn"

    user {
        base_dn = "\${..base_dn}"
        filter = "${LDAP_USER_FILTER}"
    }

    group {
        base_dn = "\${..base_dn}"
        filter = '(objectClass=posixGroup)'
        membership_attribute = 'memberOf'
    }

    client {
        base_dn = "\${..base_dn}"
        filter = '(objectClass=radiusClient)'

        attribute {
            ipaddr = 'radiusClientIdentifier'
            secret = 'radiusClientSecret'
        }
    }

    accounting {
        reference = "%{tolower:type.%{Acct-Status-Type}}"
        type {
            start {
                update {
                    description := "Online at %S"
                }
            }
            interim-update {
                update {
                    description := "Last seen at %S"
                }
            }
            stop {
                update {
                    description := "Offline at %S"
                }
            }
        }
    }

    post-auth {
        update {
            description := "Authenticated at %S"
        }
    }

    options {
        chase_referrals = yes
        rebind = yes
        res_timeout = 10
        srv_timelimit = 3
        net_timeout = 1
        idle = 60
        probes = 3
        interval = 3
        ldap_debug = 0x0028
    }

    pool {
        start = \${thread[pool].start_servers}
        min = \${thread[pool].min_spare_servers}
        max = \${thread[pool].max_servers}
        spare = \${thread[pool].max_spare_servers}
        uses = 0
        retry_delay = 30
        lifetime = 0
        idle_timeout = 60
    }
}
EOF

# Enable LDAP module
sudo ln -sf /etc/freeradius/3.0/mods-available/ldap /etc/freeradius/3.0/mods-enabled/ldap

# --------------------
# Configure mods-enabled/sql
# --------------------
echo "[INFO] Configuring mods-enabled/sql..."
sudo tee /etc/freeradius/3.0/mods-available/sql >/dev/null <<'EOF'
sql {
        dialect = "mysql"
        driver = "rlm_sql_mysql"

        mysql {
                # If any of the files below are set, TLS encryption is enabled
#               tls {
#                       ca_file = "/etc/ssl/certs/my_ca.crt"
#                       ca_path = "/etc/ssl/certs/"
#                       certificate_file = "/etc/ssl/certs/private/client.crt"
#                       private_key_file = "/etc/ssl/certs/private/client.key"
#                       cipher = "DHE-RSA-AES256-SHA:AES128-SHA"
#
#                       tls_required = yes
#                       tls_check_cert = no
#                       tls_check_cert_cn = no
#               }

                warnings = auto
        }
        # Connection info:
        #
        server = ""
        port = 3306
        login = ""
        password = ""
        radius_db = "radius"

        # and stop table in acct_table2
        acct_table1 = "radacct"
        acct_table2 = "radacct"

        # Allow for storing data after authentication
        postauth_table = "radpostauth"

        # Tables containing 'check' items
        authcheck_table = "radcheck"
        groupcheck_table = "radgroupcheck"

        # Tables containing 'reply' items
        authreply_table = "radreply"
        groupreply_table = "radgroupreply"

        # Table to keep group info
        usergroup_table = "radusergroup"

        # Remove stale session if checkrad does not see a double login
        delete_stale_sessions = yes

        pool {

                start = ${thread[pool].start_servers}n
                min = ${thread[pool].min_spare_servers}
                max = ${thread[pool].max_servers}
                spare = ${thread[pool].max_spare_servers}


                uses = 0

                retry_delay = 30

                lifetime = 0

                idle_timeout = 60
        }
        #
        read_clients = yes

        # Table to keep radius client info
        client_table = "nas"

        group_attribute = "SQL-Group"

        # Read database-specific queries
        $INCLUDE ${modconfdir}/${.:name}/main/${dialect}/queries.conf
}
EOF

# Update SQL config with DB credentials
echo "[INFO] Updating SQL config with DB credentials..."
sudo sed -i "s/^.*login\s*=.*/    login = \"radius\"/" /etc/freeradius/3.0/mods-available/sql
sudo sed -i "s/^.*password\s*=.*/    password = \"${RADIUS_DB_PASSWORD}\"/" /etc/freeradius/3.0/mods-available/sql
sudo sed -i "s/^.*server\s*=.*/    server = \"localhost\"/" /etc/freeradius/3.0/mods-available/sql

# Enable SQL module
sudo ln -sf /etc/freeradius/3.0/mods-available/sql /etc/freeradius/3.0/mods-enabled/sql

# --------------------
# Update only the post-auth section in queries.conf
# --------------------
echo "[INFO] Updating post-auth section in queries.conf to remove password storage..."

QUERIES_CONF="/etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf"

# Backup the original file
sudo cp "$QUERIES_CONF" "$QUERIES_CONF.backup_$(date +%Y%m%d_%H%M%S)"

# Replace the post-auth block
sudo sed -i '/^post-auth[[:space:]]*{/,/^}/c\
post-auth {\
        # Write SQL queries to a logfile. This is potentially useful for bulk inserts\
        # when used with the rlm_sql_null driver.\
#       logfile = ${logdir}/post-auth.sql\
\
        query = "\\\
                INSERT INTO ${..postauth_table} \\\
                        (username, reply, authdate ${..class.column_name}) \\\
                VALUES ( \\\
                        '\''%{SQL-User-Name}'\'', \\\
                        '\''%{reply:Packet-Type}'\'', \\\
                        '\''%S.%M'\'' \\\
                        ${..class.reply_xlat})"\
}' "$QUERIES_CONF"

echo "[INFO] Successfully updated post-auth section in queries.conf"

# --------------------
# Update MySQL bind address (optional)
# --------------------
MYSQL_CNF="/etc/mysql/mysql.conf.d/mysqld.cnf"
if [ -n "$BIND_ADDRESS" ]; then
    echo "[INFO] Updating MySQL bind-address to $BIND_ADDRESS..."
    sudo sed -i "s/^\s*bind-address\s*=.*/bind-address = ${BIND_ADDRESS}/" "$MYSQL_CNF"
    sudo systemctl restart mysql
fi

# --------------------
# Set proper permissions
# --------------------
echo "[INFO] Setting proper permissions..."
sudo chown -R freerad:freerad /etc/freeradius/3.0
sudo chmod 640 /etc/freeradius/3.0/mods-available/ldap
sudo chmod 640 /etc/freeradius/3.0/mods-available/sql
sudo chmod 640 /etc/freeradius/3.0/clients.conf

# --------------------
# Restart services
# --------------------
echo "[INFO] Restarting services..."
sudo systemctl restart mysql
sudo systemctl restart freeradius

# Check if FreeRADIUS started successfully
if sudo systemctl is-active --quiet freeradius; then
    echo "[SUCCESS] FreeRADIUS service is running"
else
    echo "[ERROR] FreeRADIUS failed to start. Checking logs..."
    sudo systemctl status freeradius
    echo "[INFO] Check FreeRADIUS logs: sudo tail -f /var/log/freeradius/radius.log"
fi

# --------------------
# Completion
# --------------------
echo "[SUCCESS] FreeRADIUS + MySQL + LDAP fully installed and configured."
echo "[INFO] Configuration summary:"
echo "  - MySQL database: 'radius' with user 'radius'"
echo "  - LDAP server: ${LDAP_SERVER}"
echo "  - Default site configured for LDAP authentication"
echo "  - RADIUS Secret: Using shared secret from .env"
echo "  - Clients configured: localhost, ${IP}, 192.168.0.0/16, 10.0.0.0/8"
echo "  - Inner-tunnel site: $( [ -n "$OPENVPN_AUTH" ] && [ "$OPENVPN_AUTH" = "yes" ] && echo "ENABLED" || echo "DISABLED" )"
echo "  - SQL queries updated to NOT store passwords in radpostauth table"
echo ""
echo "[INFO] Next steps:"
echo "  1. Test FreeRADIUS: sudo radtest test test localhost 0 testing123"
echo "  2. Test with shared secret: sudo radtest testuser testpass localhost 0 ${RADIUS_Secret}"
echo "  3. Configure your NAS devices to use this RADIUS server"
echo "  4. Check logs: sudo tail -f /var/log/freeradius/radius.log"
echo "  5. Test LDAP authentication with actual user credentials"
